# NUMPY

Numpy is a python package that is used for computational operations on arrays and matrices. 

This is important especially for Data Science and Machine Learning because it provides a simple and fast way of performing operations on matrices.

### How to install

In [1]:
!pip install numpy

In [2]:
import numpy as np

Using numpy to perform mathematical operations

In [3]:
a = [2, 6., 5]
b = [7, -8, -9]
c = [10, 55]
d = [14, 2.3]
e = [[2, 3., 6],
     [4, 7, 6.2]]
f = [[5.2, 5, 9],
     [8, 30, 41],
     [7, 18.2, 5]]

### Absolute
To find the absolute of an array, "np.absolute" will work the magic by returning the absolute value of whatever values are in the array or matrix. The absolute value of a number is the positive of that number computed using:

abs|X| = sqrt(X**2)

In [4]:
np.absolute(d)

array([14. ,  2.3])

In [5]:
#Notice how it returns the positive values of the elements of the array.
np.absolute(b)

array([7, 8, 9])

### Array Max

To find the maximum and minimum element in an, "np.amax" and "np.amin" returns the maximum and minimum elements respectively.

In [6]:
print(a)

#amax returns the maximum value
np.amax(a)

[2, 6.0, 5]


6.0

In [7]:
np.amin(a)

2.0

In [8]:
#amax can also return the maximum value in an axis (0 returns the maximum along the vertical axis)

print(f)
np.amax(f, axis=0)

[[5.2, 5, 9], [8, 30, 41], [7, 18.2, 5]]


array([ 8., 30., 41.])

In [9]:
#amin can also return the minimum value in an axis (1 returns the minimum value along the horizontal axis)

print(f)
np.amin(f, axis=1)

[[5.2, 5, 9], [8, 30, 41], [7, 18.2, 5]]


array([5., 8., 5.])

###  All

To test if all the elements of an array meet a certain condition, "np.all" does that by checking through the selected axis and returning the status of each element with respect to the given condition.

In [10]:
np.all(f, axis=0) < 10 #All the elements in this axis are less than 100

array([ True,  True,  True])

In [11]:
np.all(f, axis=1) > 100 #None of the elements in this axis is greater than 100

array([False, False, False])

In [12]:
np.all(b) > 3

False

###  Append

To add an element to a given array, "np.append" will attach a number to the last position in the array.

In [13]:
print(a)
s = np.append(a, 6.)
s

[2, 6.0, 5]


array([2., 6., 5., 6.])

In [14]:
#Appending a value to an matrix without specifying the axis will transform the matrix to a 1 * n dimensional array
print(f)
np.append(f, 5.4) 

[[5.2, 5, 9], [8, 30, 41], [7, 18.2, 5]]


array([ 5.2,  5. ,  9. ,  8. , 30. , 41. ,  7. , 18.2,  5. ,  5.4])

In [15]:
#You can only append a 1 * n matrix to an m * n matrix along the vertical axis (axis = 1)
np.append(f, values=[[4.2], [1.2], [10]], axis= 1)

array([[ 5.2,  5. ,  9. ,  4.2],
       [ 8. , 30. , 41. ,  1.2],
       [ 7. , 18.2,  5. , 10. ]])

In [16]:
#You can only append a m * 1 matrix to an m * n matrix along the horizontal axis (axis = 0)
np.append(f, values=[[4.2, 1.2, 10]], axis= 0)

array([[ 5.2,  5. ,  9. ],
       [ 8. , 30. , 41. ],
       [ 7. , 18.2,  5. ],
       [ 4.2,  1.2, 10. ]])

###  Broadcast

To broadcast the shape and values of an array to another array, "np.broadcast" casts the elements of the first array to fill the shape of the second.

In [17]:
print(a)
print(b)
braodcasted = np.broadcast(a, f)
print(braodcasted.shape)

[2, 6.0, 5]
[7, -8, -9]
(3, 3)


In [18]:
#You can only broadcast the shape of a larger array to a smaller array
minimize = np.broadcast(f, a)
print(minimize.shape)

(3, 3)


###  ARange

This is the numpy function of provide a range of values.

In [19]:
np.arange(10, 52)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51])

In [20]:
np.arange(0, 50, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

###  Dot

This provides the dotproduct of two array.

In [21]:
#The dotproduct of two arrays of the same shape can be computed.
np.dot(a, b)

-79.0

In [22]:
#The dotproduct of an array and a matrix can be computed as seen below:
np.dot(a, f)

array([ 93.4, 281. , 289. ])

###  Cummulative Sum

This provides the across a chosen axis.

In [23]:
#If an axis is not stated, numpy interpretes and converts the arrays/matrix to a 1 * n dimensional array
print(np.cumsum(f))

[  5.2  10.2  19.2  27.2  57.2  98.2 105.2 123.4 128.4]


In [24]:
print(f)
np.cumsum(f, axis=1)

[[5.2, 5, 9], [8, 30, 41], [7, 18.2, 5]]


array([[ 5.2, 10.2, 19.2],
       [ 8. , 38. , 79. ],
       [ 7. , 25.2, 30.2]])

In [25]:
np.cumsum(f, axis=0)

array([[ 5.2,  5. ,  9. ],
       [13.2, 35. , 50. ],
       [20.2, 53.2, 55. ]])

###  Reshape

This function transforms the shape of an array into another specified shape. Meanwhile it cannot reshape an array of b-elements into an array of c-elements, that is, an array of 9 elements cannot be reshaped into an array of 6 elements.

In [26]:
print(a)
np.reshape(a, [3,1])

[2, 6.0, 5]


array([[2.],
       [6.],
       [5.]])

In [27]:
print(f)
np.reshape(f, 9)

[[5.2, 5, 9], [8, 30, 41], [7, 18.2, 5]]


array([ 5.2,  5. ,  9. ,  8. , 30. , 41. ,  7. , 18.2,  5. ])

###  Resize

This function changes the size of an array or matrix into a specified size.

In [28]:
print(a)
np.resize(a, [3,2])

[2, 6.0, 5]


array([[2., 6.],
       [5., 2.],
       [6., 5.]])

In [29]:
print(f)
np.resize(f, [9,3])

[[5.2, 5, 9], [8, 30, 41], [7, 18.2, 5]]


array([[ 5.2,  5. ,  9. ],
       [ 8. , 30. , 41. ],
       [ 7. , 18.2,  5. ],
       [ 5.2,  5. ,  9. ],
       [ 8. , 30. , 41. ],
       [ 7. , 18.2,  5. ],
       [ 5.2,  5. ,  9. ],
       [ 8. , 30. , 41. ],
       [ 7. , 18.2,  5. ]])

'''

Resize is different from Reshape because *reshape* cannot transform an array of b-elements into an array of c-elements, 
that is, an array of 9 elements cannot be reshaped into an array of 6 elements while resize can.

'''

In [32]:
print(np.resize(f, [2,5]))
'''
while

print(np.reshape(f, [2,5]))

will give an error

'''

[[ 5.2  5.   9.   8.  30. ]
 [41.   7.  18.2  5.   5.2]]


'\nwhile\n\nprint(np.reshape(f, [2,5]))\n\nwill give an error\n\n'

###  Vstack

This reshapes an array/matrix by converting it to stack on the vertical axis.

In [33]:
np.vstack(a)

array([[2.],
       [6.],
       [5.]])

Hstack reshapes an array/matrix by appending the rows along one dimension.

In [34]:
np.hstack(f)

array([ 5.2,  5. ,  9. ,  8. , 30. , 41. ,  7. , 18.2,  5. ])

###  Unique

This returns a list of the unique element in a array

In [35]:
np.unique(a)

array([2., 5., 6.])

In [36]:
np.unique(f)

array([ 5. ,  5.2,  7. ,  8. ,  9. , 18.2, 30. , 41. ])

###  Random

This generates a random set of values.

In [37]:
np.random.geometric(0.5, 100)

array([3, 1, 1, 1, 5, 1, 2, 1, 1, 2, 2, 2, 1, 1, 5, 2, 1, 2, 2, 1, 1, 1,
       4, 2, 2, 1, 1, 3, 4, 3, 1, 3, 2, 1, 2, 1, 1, 1, 1, 1, 1, 3, 3, 2,
       1, 1, 1, 3, 1, 3, 1, 4, 1, 1, 1, 7, 2, 2, 1, 1, 2, 3, 2, 7, 2, 1,
       3, 1, 2, 4, 1, 1, 1, 1, 1, 1, 3, 1, 3, 2, 1, 2, 1, 2, 1, 2, 1, 2,
       3, 6, 1, 2, 1, 2, 2, 1, 1, 4, 1, 1])

In [38]:
np.random.randint(10, 50, 200)

array([18, 11, 33, 36, 38, 26, 20, 24, 11, 33, 44, 31, 23, 32, 44, 28, 18,
       36, 19, 33, 17, 29, 28, 46, 41, 24, 32, 18, 38, 11, 19, 40, 17, 17,
       17, 20, 46, 42, 23, 38, 31, 40, 28, 43, 32, 31, 33, 22, 38, 42, 26,
       26, 49, 21, 14, 12, 46, 19, 36, 17, 36, 19, 41, 28, 16, 33, 21, 16,
       10, 36, 36, 38, 14, 23, 20, 47, 47, 15, 45, 44, 10, 22, 32, 29, 38,
       30, 41, 40, 47, 10, 35, 31, 25, 26, 45, 39, 24, 36, 30, 47, 31, 39,
       47, 13, 16, 27, 12, 32, 40, 45, 15, 19, 22, 21, 11, 35, 30, 23, 30,
       20, 29, 30, 32, 43, 12, 47, 23, 21, 41, 38, 32, 35, 36, 45, 28, 17,
       31, 14, 20, 17, 17, 29, 11, 36, 32, 45, 37, 30, 16, 31, 47, 17, 31,
       33, 22, 41, 14, 39, 39, 48, 13, 14, 20, 36, 23, 40, 17, 40, 30, 35,
       22, 11, 25, 17, 18, 22, 45, 29, 27, 12, 30, 26, 24, 31, 45, 29, 13,
       45, 17, 29, 40, 40, 16, 20, 43, 22, 23, 48, 39, 39])

In [39]:
#This can also be converted into an array
np.random.randint(10, 50, [3, 6])

array([[30, 39, 34, 19, 34, 29],
       [33, 35, 16, 10, 41, 34],
       [29, 14, 23, 42, 26, 44]])

###  Sort

This function rearranges the values of an array/matrix.

In [40]:
np.sort(a)

array([2., 5., 6.])

In [41]:
print(f)
np.sort(f)

[[5.2, 5, 9], [8, 30, 41], [7, 18.2, 5]]


array([[ 5. ,  5.2,  9. ],
       [ 8. , 30. , 41. ],
       [ 5. ,  7. , 18.2]])

###  Square

This returns the square of an integer, list or matrix

In [42]:
np.square(4)

16

In [43]:
np.square([1, 5, 8])

array([ 1, 25, 64], dtype=int32)

In [44]:
np.square(f)

array([[  27.04,   25.  ,   81.  ],
       [  64.  ,  900.  , 1681.  ],
       [  49.  ,  331.24,   25.  ]])